//! Wire spelling of field enums generated by the backend `CkField` derive.

use crudkit_rs::data::{Field, FieldLookup};
use crudkit_rs_macros::CkField;

#[derive(Clone, Debug, CkField)]
pub struct Person {
    pub id: i64,
    pub first_name: String,
}

#[test]
fn field_enums_serialize_as_their_field_names() {
    let json = serde_json::to_value(PersonField::FirstName).expect("field should serialize");

    assert_eq!(json, serde_json::json!("first_name"));
    assert_eq!(json, serde_json::json!(PersonField::FirstName.name()));
}

#[test]
fn field_enums_deserialize_from_the_names_used_by_conditions() {
    let field: PersonField =
        serde_json::from_str("\"first_name\"").expect("field name should deserialize");

    assert_eq!(field, PersonField::FirstName);
    assert_eq!(PersonField::from_name("first_name"), Some(field));
    assert!(serde_json::from_str::<PersonField>("\"FirstName\"").is_err());
}
