[package]
name = "derive-crud-action-payload"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/progress.rs"

[dependencies]
darling = { workspace = true }
proc-macro-error = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
crudkit-web = { path = "../crudkit-web" }
serde = "1"
trybuild = { version = "1", features = ["diff"] }
