[package]
name = "crudkit-core-macros"
version = "0.1.0"
edition = "2024"
description = "CkId derive macro for crudkit"
autotests = false

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/progress.rs"

[dependencies]
crudkit-core = { path = "../crudkit-core", default-features = false }
darling = { workspace = true }
indoc = { version = "2.0.7", default-features = false }
proc-macro-error2 = { workspace = true }
proc-macro-type-name = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
assertr = { version = "0.7.1", default-features = false }
serde = { version = "1.0.229", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0.151", default-features = false, features = ["alloc"] }
time = { version = "0.3.55", default-features = false, features = ["serde", "std"] }
trybuild = { version = "1.0.121", default-features = false, features = ["diff"] }
uuid = { version = "1.27.0", default-features = false, features = ["serde", "v4"] }
