[workspace]
members = ["crates/*"]
default-members = ["crates/crudkit-id"]

[workspace.dependencies]
proc-macro-type-name = "0.1.0"
darling = "0.20.3"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.65"
quote = "1.0.30"
syn = { version = "2.0.26", features = ["extra-traits"] }
