[workspace]
resolver = "2"
members = [
    "crudkit-core",
    "crudkit-core-macro-util",
    "crudkit-core-macros",
    "crudkit-leptos",
    "crudkit-rs",
    "crudkit-rs-macros",
    "crudkit-rs-macros-core",
    "crudkit-sea-orm",
    "crudkit-sea-orm-macros",
    "crudkit-web",
    "crudkit-web-macros",
    "crudkit-wire-format",
]

[workspace.dependencies]
darling = { version = "0.24.1", default-features = false }
proc-macro-type-name = { version = "0.1.0", default-features = false }
proc-macro2 = { version = "1.0.107", default-features = false }
quote = { version = "1.0.47", default-features = false }
syn = { version = "3.0.6", default-features = false, features = ["derive", "parsing", "printing", "proc-macro"] }
