[package]
name = "create-id-impl"
version = "0.0.1"
edition = "2021"

[dependencies]
derive-helper = { workspace = true }
darling = { workspace = true }
proc-macro-error = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
