//! Type-erased (dynamic) types for runtime polymorphism.
//!
//! These types allow crudkit-leptos components to work with any resource type
//! without knowing concrete types at compile time.
//!
//! # Three-Tier Type Erasure Pattern
//!
//! The framework uses a consistent three-tier pattern for runtime polymorphism:
//!
//! | Tier | Pattern | Purpose | Example |
//! |------|---------|---------|---------|
//! | 1 | Typed traits | Compile-time generic code | `Model`, `FieldAccess<T>` |
//! | 2 | `Erased*` traits | Object-safe trait objects | `ErasedModel`, `ErasedField` |
//! | 3 | `Dyn*` wrappers | Boxed/Arc wrappers with helpers | `DynReadModel`, `DynCreateField` |
//!
//! ## Why Three Tiers?
//!
//! - **Tier 1 (Typed)**: Provides full type safety and zero-cost abstractions. Used when
//!   concrete types are known at compile time.
//!
//! - **Tier 2 (Erased)**: Makes traits dyn-compatible by removing generic parameters.
//!   Uses `#[typetag::serde]` for serialization and `downcast_rs` for type recovery.
//!
//! - **Tier 3 (Dyn wrappers)**: Provides ergonomic wrappers around `Box<dyn Erased*>` or
//!   `Arc<dyn Erased*>` with convenience methods like `downcast_ref<T>()`.
//!
//! ## Conversion Flow
//!
//! ```text
//! T: Model  →  derived ErasedReadModel  →  wrap in DynReadModel  →  downcast<T>() when needed
//! ```
//!
//! ## Naming Conventions
//!
//! - `Erased*` prefix: Traits for type-erased behavior (e.g., `ErasedModel`)
//! - `Dyn*` prefix: Boxed trait object wrappers (e.g., `DynReadModel` wraps `Box<dyn ErasedReadModel>`)
//!
//! The wrappers provide:
//! - `new(concrete)` - Create from concrete type
//! - `downcast<T>()` - Consume and recover concrete type (panics on mismatch)
//! - `downcast_ref<T>()` - Borrow as concrete type (panics on mismatch)
//! - `downcast_mut<T>()` - Mutably borrow as concrete type (panics on mismatch)

use crudkit_core::{Named, Value};
use dyn_clone::DynClone;
use dyn_eq::DynEq;
use dyn_hash::DynHash;
use serde::Serialize;
use serde::de::DeserializeOwned;
use std::fmt::Debug;
use std::hash::Hash;
use std::sync::Arc;

/// Trait for typed model access in the frontend.
///
/// This extends the base `Model` trait from crudkit-core with frontend-specific
/// requirements for serialization, field enumeration, and value access.
///
/// Note: This does not have `HasId` as a supertrait, as not all data models
/// (namely the `CreateModel`) can supply an ID!
///
/// The bounds are a superset of `crudkit_core::Model`, so any type implementing
/// this trait also satisfies the core Model trait.
pub trait Model:
    PartialEq + Clone + Debug + Serialize + DeserializeOwned + Send + Sync + 'static
{
    type Field: Named
        + FieldAccess<Self>
        + PartialEq
        + Eq
        + Hash
        + Clone
        + Debug
        + Serialize
        + DeserializeOwned
        + Send
        + Sync
        + 'static;

    /// Returns every field of the model.
    fn all_fields() -> Vec<Self::Field>;

    /// Returns the field named `field_name`, or `None` if the model has no such field.
    fn field(field_name: &str) -> Option<Self::Field>;
}

/// Trait for typed field value access.
///
/// This is the frontend's field trait, used for:
/// - Reading field values from entities (`value()`)
/// - Writing field values to entities (`set_value()`)
/// - Querying field metadata like type and optionality
///
/// **Comparison with `crudkit_rs::Field`:**
/// - `crudkit_rs::Field` provides **metadata only** - field names for query building
/// - `FieldAccess<T>` (this trait) provides **value access** - getting and setting field values
///
/// The distinction exists because:
/// - Backend code uses `SeaORM`'s `ModelTrait` for value access, so its `Field` trait only needs
///   name metadata for query construction.
/// - Frontend code builds reactive forms and needs to read/write field values generically,
///   so it requires the full `FieldAccess<T>` trait.
///
/// Note: Frontend field enums implement both `Named` (for field names, analogous to backend
/// `Field::name()`) and `FieldAccess<T>` (for value operations).
///
/// Field enums implementing this trait are generated by the `CkField` derive macro in crudkit-web.
pub trait FieldAccess<T> {
    /// Returns the value of this field from the entity.
    fn value(&self, entity: &T) -> Value;

    /// Sets the value of this field on the entity.
    fn set_value(&self, entity: &mut T, value: Value);

    /// Returns the kind of value this field holds.
    fn value_kind(&self) -> crudkit_core::ValueKind;

    /// Returns whether this field is optional.
    fn is_optional(&self) -> bool;
}

// Identification of erased models is shared with the backend.
pub use crudkit_core::id::DynIdentifiable;
pub use crudkit_core::id::ErasedIdentifiable;

#[typetag::serde]
pub trait ErasedModel:
    ErasedIdentifiable + Debug + DynClone + DynEq + downcast_rs::Downcast + Send + Sync
{
}
dyn_eq::eq_trait_object!(ErasedModel);
dyn_clone::clone_trait_object!(ErasedModel);
downcast_rs::impl_downcast!(ErasedModel);

// Note: Every ErasedCreateModel needs to be `Default`, but that would introduce a `Sized` bound,
// rendering this trait dyn-incompatible.
#[typetag::serde]
pub trait ErasedCreateModel: ErasedModel {}
dyn_eq::eq_trait_object!(ErasedCreateModel);
dyn_clone::clone_trait_object!(ErasedCreateModel);
downcast_rs::impl_downcast!(ErasedCreateModel);

#[typetag::serde]
pub trait ErasedUpdateModel: ErasedModel {}
dyn_eq::eq_trait_object!(ErasedUpdateModel);
dyn_clone::clone_trait_object!(ErasedUpdateModel);
downcast_rs::impl_downcast!(ErasedUpdateModel);

#[typetag::serde]
pub trait ErasedReadModel: ErasedModel {}
dyn_eq::eq_trait_object!(ErasedReadModel);
dyn_clone::clone_trait_object!(ErasedReadModel);
downcast_rs::impl_downcast!(ErasedReadModel);

macro_rules! impl_dyn_model {
    ($dyn_ty:tt, $erased_ty:tt) => {
        /// Any type-erased (boxed) model.
        #[derive(Debug, Clone, Eq)]
        pub struct $dyn_ty {
            pub(crate) inner: Box<dyn $erased_ty>,
        }

        impl PartialEq for $dyn_ty {
            fn eq(&self, other: &Self) -> bool {
                self.inner.dyn_eq(DynEq::as_any(&other.inner))
            }
        }

        impl<T: $erased_ty> From<T> for $dyn_ty {
            fn from(value: T) -> Self {
                Self {
                    inner: Box::new(value),
                }
            }
        }

        impl $dyn_ty {
            pub fn new<Concrete: $erased_ty>(concrete: Concrete) -> Self {
                Self {
                    inner: Box::new(concrete),
                }
            }

            pub fn downcast<Concrete: $erased_ty>(self) -> Concrete {
                *self.inner.downcast::<Concrete>().expect("correct")
            }

            pub fn downcast_ref<Concrete: $erased_ty>(&self) -> &Concrete {
                self.inner.downcast_ref::<Concrete>().expect("correct")
            }

            pub fn downcast_mut<Concrete: $erased_ty>(&mut self) -> &mut Concrete {
                self.inner.downcast_mut::<Concrete>().expect("correct")
            }

            /// Serializes the model as plain JSON, without the type tag of its erased
            /// serialization.
            ///
            /// # Errors
            ///
            /// Returns an error if the model cannot be serialized, or if its erased serialization
            /// is not an object with exactly one type-tag entry.
            pub fn to_untagged_json(&self) -> Result<serde_json::Value, UntaggedJsonError> {
                untagged_json(&self.inner)
            }
        }

        impl std::ops::Deref for $dyn_ty {
            type Target = dyn $erased_ty;

            fn deref(&self) -> &Self::Target {
                self.inner.as_ref()
            }
        }
    };
}

/// Failure to serialize an erased model without its type tag.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum UntaggedJsonError {
    /// The model could not be serialized.
    #[error("failed to serialize the model: {0}")]
    Serialize(String),
    /// The erased serialization did not wrap the model in exactly one type-tag entry.
    #[error("expected the model to be wrapped in exactly one type-tag entry, found {0}")]
    UnexpectedShape(&'static str),
}

/// Serializes `model` and unwraps the externally tagged object produced by typetag.
fn untagged_json(
    model: &impl erased_serde::Serialize,
) -> Result<serde_json::Value, UntaggedJsonError> {
    let value = erased_serde::serialize(model, serde_json::value::Serializer)
        .map_err(|e| UntaggedJsonError::Serialize(e.to_string()))?;
    match value {
        serde_json::Value::Object(object) if object.len() == 1 => object
            .into_values()
            .next()
            .ok_or(UntaggedJsonError::UnexpectedShape("an empty object")),
        serde_json::Value::Object(_) => Err(UntaggedJsonError::UnexpectedShape(
            "an object with several entries",
        )),
        serde_json::Value::Null => Err(UntaggedJsonError::UnexpectedShape("null")),
        serde_json::Value::Bool(_) => Err(UntaggedJsonError::UnexpectedShape("a boolean")),
        serde_json::Value::Number(_) => Err(UntaggedJsonError::UnexpectedShape("a number")),
        serde_json::Value::String(_) => Err(UntaggedJsonError::UnexpectedShape("a string")),
        serde_json::Value::Array(_) => Err(UntaggedJsonError::UnexpectedShape("an array")),
    }
}

impl_dyn_model!(DynCreateModel, ErasedCreateModel);
impl_dyn_model!(DynReadModel, ErasedReadModel);
impl_dyn_model!(DynUpdateModel, ErasedUpdateModel);

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DynReadOrUpdateModel {
    Read(DynReadModel),
    Update(DynUpdateModel),
}

impl From<DynReadModel> for DynReadOrUpdateModel {
    fn from(model: DynReadModel) -> Self {
        Self::Read(model)
    }
}

impl From<DynUpdateModel> for DynReadOrUpdateModel {
    fn from(model: DynUpdateModel) -> Self {
        Self::Update(model)
    }
}

/// This trait is implemented for each derived type (enum) describing a models fields.
///
/// Writing values is role-specific and therefore declared by `ErasedCreateField`, `ErasedReadField`,
/// and `ErasedUpdateField`.
#[typetag::serde]
pub trait ErasedField: Debug + Named + DynClone + DynEq + DynHash + Send + Sync {
    /// Returns the kind of value this field holds.
    fn value_kind(&self) -> crudkit_core::ValueKind;

    /// Returns whether this field is optional.
    fn is_optional(&self) -> bool;
}
dyn_eq::eq_trait_object!(ErasedField);
dyn_clone::clone_trait_object!(ErasedField);
dyn_hash::hash_trait_object!(ErasedField);

/// A field known to be part of a `create` model. The type erased version is `DynCreateField`.
#[typetag::serde]
pub trait ErasedCreateField: ErasedField {
    /// Writes `value` into this field of `model`.
    fn set_value(&self, model: &mut DynCreateModel, value: Value);
}
dyn_eq::eq_trait_object!(ErasedCreateField);
dyn_clone::clone_trait_object!(ErasedCreateField);
dyn_hash::hash_trait_object!(ErasedCreateField);

/// A field known to be part of a `read` model. The type erased version is `DynReadField`.
#[typetag::serde]
pub trait ErasedReadField: ErasedField {
    /// Writes `value` into this field of `model`.
    fn set_value(&self, model: &mut DynReadModel, value: Value);
}
dyn_eq::eq_trait_object!(ErasedReadField);
dyn_clone::clone_trait_object!(ErasedReadField);
dyn_hash::hash_trait_object!(ErasedReadField);

/// A field known to be part of an `update` model. The type erased version is `DynUpdateField`.
#[typetag::serde]
pub trait ErasedUpdateField: ErasedField {
    /// Writes `value` into this field of `model`.
    fn set_value(&self, model: &mut DynUpdateModel, value: Value);
}
dyn_eq::eq_trait_object!(ErasedUpdateField);
dyn_clone::clone_trait_object!(ErasedUpdateField);
dyn_hash::hash_trait_object!(ErasedUpdateField);

/// Marker trait for type-erased field wrappers (`DynCreateField`, `DynReadField`, `DynUpdateField`).
///
/// This trait is implemented for the `Dyn*Field` wrapper types to provide a common
/// abstraction over all type-erased fields regardless of their model type.
pub trait TypeErasedField:
    Named + Debug + Clone + PartialEq + Eq + Hash + Send + Sync + 'static
{
    /// The type-erased model this field belongs to.
    type Model: Debug + Clone + PartialEq + Send + Sync + 'static;

    /// Writes `value` into this field of `model`.
    fn set_value(&self, model: &mut Self::Model, value: Value);

    /// Returns the kind of value this field holds.
    fn value_kind(&self) -> crudkit_core::ValueKind;

    /// Returns whether this field is optional.
    fn is_optional(&self) -> bool;
}

macro_rules! impl_dyn_field {
    ($dyn_ty:tt, $erased_ty:tt, $dyn_model_ty:tt) => {
        /// Any field. Usable in collections.
        #[derive(Debug, Clone, Eq, serde::Serialize, serde::Deserialize)]
        pub struct $dyn_ty {
            inner: Arc<dyn $erased_ty>,
        }

        impl PartialEq for $dyn_ty {
            fn eq(&self, other: &Self) -> bool {
                self.inner.dyn_eq(DynEq::as_any(&other.inner))
            }
        }

        impl std::hash::Hash for $dyn_ty {
            fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
                self.inner.dyn_hash(state);
            }
        }

        impl<T: $erased_ty> From<T> for $dyn_ty {
            fn from(value: T) -> Self {
                Self {
                    inner: Arc::new(value),
                }
            }
        }

        impl $dyn_ty {
            pub fn new<Concrete: $erased_ty>(concrete: Concrete) -> Self {
                Self {
                    inner: Arc::new(concrete),
                }
            }
        }

        impl std::ops::Deref for $dyn_ty {
            type Target = dyn $erased_ty;

            fn deref(&self) -> &Self::Target {
                self.inner.as_ref()
            }
        }

        impl Named for $dyn_ty {
            fn name(&self) -> std::borrow::Cow<'static, str> {
                self.inner.name()
            }
        }

        impl TypeErasedField for $dyn_ty {
            type Model = $dyn_model_ty;

            fn set_value(&self, model: &mut $dyn_model_ty, value: Value) {
                $erased_ty::set_value(self.inner.as_ref(), model, value);
            }

            fn value_kind(&self) -> crudkit_core::ValueKind {
                self.inner.value_kind()
            }

            fn is_optional(&self) -> bool {
                self.inner.is_optional()
            }
        }
    };
}

impl_dyn_field!(DynCreateField, ErasedCreateField, DynCreateModel);
impl_dyn_field!(DynReadField, ErasedReadField, DynReadModel);
impl_dyn_field!(DynUpdateField, ErasedUpdateField, DynUpdateModel);

/// A field of a create, read, or update model, convertible into the type-erased field of its
/// model's kind.
///
/// The `CkField` derive implements it for every field enum: a field of a create model converts
/// into a [`DynCreateField`], one of a read model into a [`DynReadField`], and one of an update
/// model into a [`DynUpdateField`]. This lets generic code, e.g. a form field component taking
/// `Club::Name`, find the state of the matching form by type.
pub trait IntoDynField: Clone + Send + Sync + 'static {
    /// The type-erased field type of this field's model kind.
    type Dyn: TypeErasedField;

    /// Converts this field into its type-erased form.
    fn into_dyn(self) -> Self::Dyn;
}

impl IntoDynField for DynCreateField {
    type Dyn = Self;

    fn into_dyn(self) -> Self {
        self
    }
}

impl IntoDynField for DynReadField {
    type Dyn = Self;

    fn into_dyn(self) -> Self {
        self
    }
}

impl IntoDynField for DynUpdateField {
    type Dyn = Self;

    fn into_dyn(self) -> Self {
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use assertr::prelude::*;

    #[test]
    fn untagged_json_unwraps_the_type_tag() {
        let tagged = serde_json::json!({ "ReadItem": { "id": 1 } });

        assert_that!(untagged_json(&tagged)).is_equal_to(Ok(serde_json::json!({ "id": 1 })));
    }

    #[test]
    fn untagged_json_rejects_values_without_exactly_one_tag() {
        assert_that!(untagged_json(&serde_json::json!({ "a": 1, "b": 2 }))).is_equal_to(Err(
            UntaggedJsonError::UnexpectedShape("an object with several entries"),
        ));
        assert_that!(untagged_json(&serde_json::json!([1])))
            .is_equal_to(Err(UntaggedJsonError::UnexpectedShape("an array")));
    }
}
