[package]
name = "crudkit-websocket"
version = "0.1.0"
edition = "2021"

[dependencies]
crudkit-id = { path = "../crudkit-id/crates/crudkit-id" }
crudkit-validation = { path = "../crudkit-validation" }

serde = { version = "1.0.192", features = ["derive"] }
