//! Storage-agnostic data traits for CRUD operations.
//!
//! These traits define the core abstractions for models and fields without
//! coupling to any specific storage backend (like SeaORM).
//!
//! # Marker Trait Convention
//!
//! This module defines marker traits that bundle common trait bounds for specific model roles:
//!
//! | Trait | Role | Key Bounds |
//! |-------|------|------------|
//! | [`CreateModel`] | Entity creation DTOs | `Model + DeserializeOwned` |
//! | [`UpdateModel`] | Entity update DTOs | `Model + DeserializeOwned` |
//! | [`ReadModel`] | Query result entities | `Model + HasId + Serialize` |
//!
//! These traits don't add new methods—they exist to:
//! 1. Bundle the required bounds in one place for cleaner trait bounds elsewhere.
//! 2. Provide semantic meaning about a model's role in CRUD operations.
//! 3. Allow storage backends to add implementation-specific behavior (see
//!    `crudkit-sea-orm::SeaOrmCreateModel` and `crudkit-sea-orm::SeaOrmUpdateModel`).
//!
//! `UpdateModel` and `ReadModel` have blanket implementations, so any type meeting their
//! bounds automatically implements them. `CreateModel` requires explicit implementation
//! (typically via the `CkCreateModel` or `CkSeaOrmCreateModel` derive macros) because
//! create models often need storage-specific conversion logic.

use crudkit_core::condition::ConditionClauseValue;
use crudkit_core::Value;
use serde::{de::DeserializeOwned, Serialize};
use std::fmt::Debug;
use std::hash::Hash;

/// Trait for models with typed field access.
///
/// This is the backend's model trait. Its bounds are a superset of `crudkit_core::Model`,
/// meaning any type implementing this trait also satisfies the core Model trait bounds.
///
/// Each model type (ReadModel, CreateModel, UpdateModel) implements this
/// trait with its own Field enum for typed field access.
pub trait Model: Clone + Debug + Send + Sync + 'static {
    /// The field enum for this model, providing typed access to field values.
    type Field: Field;
}

/// Trait for field enums that provide metadata about model fields.
///
/// This is the backend's field trait, used primarily for:
/// - Field name access (for serialization, query building, condition parsing)
/// - Mapping between string field names and typed field variants
///
/// **Comparison with `crudkit_web::FieldAccess<T>`:**
/// - `Field` (this trait) provides **metadata** - it answers "what is this field's name?"
/// - `FieldAccess<T>` provides **value access** - it answers "what is the value of this field
///   on a given entity?" and "how do I update it?"
///
/// The distinction exists because:
/// - Backend code needs field names for SQL query generation, but doesn't need value access
///   at the trait level (SeaORM handles that via its `ModelTrait`).
/// - Frontend code needs both field names (via `Named` supertrait) AND value access for
///   building reactive forms.
///
/// Field enums are generated by the `CkField` derive macro.
pub trait Field: Clone + Eq + Hash + Debug + Send + Sync + 'static {
    /// Returns the field name as a static string.
    fn name(&self) -> &'static str;
}

/// Trait for looking up fields by name.
///
/// Used for dynamic field access, such as when parsing filter conditions
/// from JSON where field names are provided as strings.
pub trait FieldLookup: Sized {
    /// Attempt to find a field by its string name.
    /// Returns `None` if no field with that name exists.
    fn from_name(name: &str) -> Option<Self>;
}

/// Trait for converting condition values to typed values.
///
/// Used when building queries from parsed filter conditions.
/// Each field knows how to convert a `ConditionClauseValue` to its expected type.
pub trait ConditionValueConverter {
    /// Convert a condition clause value to a typed Value for this field.
    fn convert_condition_value(&self, value: ConditionClauseValue) -> Result<Value, String>;
}

/// Re-export `HasId` from crudkit-id.
pub use crudkit_core::id::HasId;

/// Marker trait for the model type used to create a new entity.
///
/// They typically lack fields which get auto-generated upon first storage by the storage backend.
///
/// No general transformation into any other model type is defined by crudkit. The transformation
/// happens inside the `Repository`.
///
/// Storage integrations, like `crudkit-sea-orm`, however, will provide means to convert a
/// `CreateModel` into the main (persisted) `Model`.
pub trait CreateModel: Model + DeserializeOwned + Debug + Clone + Send + Sync + 'static {}

/// Marker trait for update models.
///
/// Update models are DTOs used to update existing entities. They may
/// contain the entity's ID for identification.
pub trait UpdateModel: Model + DeserializeOwned + Debug + Clone + Send + Sync + 'static {}

/// Marker trait for read models.
///
/// Read models represent entities as returned from queries. They always
/// have an ID and are serializable for API responses.
pub trait ReadModel: Model + HasId + Serialize + Clone + Send + Sync + 'static {}

// Blanket implementations for convenience.
impl<T> UpdateModel for T where T: Model + DeserializeOwned + Debug + Clone + Send + Sync + 'static {}
impl<T> ReadModel for T where T: Model + HasId + Serialize + Clone + Send + Sync + 'static {}
