//! Storage-agnostic data traits for CRUD operations.
//!
//! These traits define the core abstractions for models and fields without
//! coupling to any specific storage backend (like SeaORM).

use crudkit_core::condition::ConditionClauseValue;
use crudkit_core::Value;
use serde::{de::DeserializeOwned, Serialize};
use std::fmt::Debug;
use std::hash::Hash;

/// Trait for models with typed field access.
///
/// This is the backend's model trait. Its bounds are a superset of `crudkit_core::Model`,
/// meaning any type implementing this trait also satisfies the core Model trait bounds.
///
/// Each model type (ReadModel, CreateModel, UpdateModel) implements this
/// trait with its own Field enum for typed field access.
pub trait Model: Clone + Debug + Send + Sync + 'static {
    /// The field enum for this model, providing typed access to field values.
    type Field: Field;
}

/// Backward compatibility alias.
pub use Model as CrudModel;

/// Trait for field enums that provide typed access to model fields.
///
/// Field enums are generated by derive macros and provide:
/// - Field name access for serialization/querying
/// - Type-safe field value extraction and mutation
pub trait Field: Clone + Eq + Hash + Debug + Send + Sync + 'static {
    /// Returns the field name as a static string.
    fn name(&self) -> &'static str;
}

/// Backward compatibility alias.
pub use Field as FieldTrait;

/// Trait for looking up fields by name.
///
/// Used for dynamic field access, such as when parsing filter conditions
/// from JSON where field names are provided as strings.
pub trait FieldLookup: Sized {
    /// Attempt to find a field by its string name.
    /// Returns `None` if no field with that name exists.
    fn from_name(name: &str) -> Option<Self>;
}

/// Trait for converting condition values to typed values.
///
/// Used when building queries from parsed filter conditions.
/// Each field knows how to convert a `ConditionClauseValue` to its expected type.
pub trait ConditionValueConverter {
    /// Convert a condition clause value to a typed Value for this field.
    fn convert_condition_value(&self, value: ConditionClauseValue) -> Result<Value, String>;
}

/// Re-export `HasId` from crudkit-id.
pub use crudkit_core::id::HasId;

/// Alias for backward compatibility.
pub use crudkit_core::id::HasId as CrudIdTrait;

/// Marker trait for the model type used to create a new entity.
///
/// They typically lack fields which get auto-generated upon first storage by the storage backend.
///
/// No general transformation into any other model type is defined by crudkit. The transformation
/// happens inside the `Repository`.
///
/// Storage integrations, like `crudkit-sea-orm`, however, will provide means to convert a
/// `CreateModel` into the main (persisted) `Model`.
pub trait CreateModelTrait: Model + DeserializeOwned + Debug + Clone + Send + Sync + 'static {}

/// Marker trait for update models.
///
/// Update models are DTOs used to update existing entities. They may
/// contain the entity's ID for identification.
pub trait UpdateModelTrait: Model + DeserializeOwned + Debug + Clone + Send + Sync + 'static {}

/// Marker trait for read models.
///
/// Read models represent entities as returned from queries. They always
/// have an ID and are serializable for API responses.
pub trait ReadModelTrait: Model + CrudIdTrait + Serialize + Clone + Send + Sync + 'static {}

// Blanket implementations for convenience.
impl<T> UpdateModelTrait for T where T: Model + DeserializeOwned + Debug + Clone + Send + Sync + 'static
{
}
impl<T> ReadModelTrait for T where T: Model + CrudIdTrait + Serialize + Clone + Send + Sync + 'static
{
}
