[package]
name = "crud-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
# Internal
axum-websockets = {path = "../../../../axum-websockets"}
crud-shared-types = {path = "../../../crud-shared-types"}
chrono-utc-date-time = {path = "../../../../chrono-utc-date-time", features = [ "sea-orm" ]}

# Macros
derive-crud-columns = { path = "../derive-crud-columns" }
derive-create-model = { path = "../derive-create-model" }
derive-update-model = { path = "../derive-update-model" }

# External
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
chrono = "0.4.22"
axum = "0.5.16"
indexmap = { version = "1.9.1", features = ["serde"] }
paste = "1.0.9"
log = "0.4.17"
async-trait = "0.1.57"

sea-orm = { version = "0.9.2", features = [ "debug-print", "runtime-tokio-rustls", "sqlx", "sqlx-postgres" ] }
sea-query = { version = "0.26.3" }
sea-schema = { version = "0.9.4", default-features = false, features = [ "debug-print" ] }
