use crate::{
    auth::RequestContext,
    error::CrudError,
    lifetime::CrudLifetime,
    prelude::*,
    validation,
    validation::{
        into_persistable, run_entity_validation, run_global_validation, CrudAction, ValidationContext,
        ValidationTrigger, When,
    },
    GetIdFromModel,
};

use crudkit_collaboration::{CollabMessage, EntityCreated};
use crudkit_core::Saved;
use crudkit_id::{Id, SerializableId};
use crudkit_validation::PartialSerializableValidations;

use serde::Deserialize;
use std::{collections::HashMap, sync::Arc};
use utoipa::ToSchema;

#[derive(Debug, ToSchema, Deserialize)]
pub struct CreateOne<T> {
    pub entity: T,
}

#[tracing::instrument(level = "info", skip(context, request))]
pub async fn create_one<R: CrudResource>(
    request: RequestContext<R::Auth>,
    context: Arc<CrudContext<R>>,
    body: CreateOne<R::CreateModel>,
) -> Result<Saved<R::Model>, CrudError> {
    // Use the "CreateModel" to deserialize the given JSON. Some not required members are allowed to be missing.
    let create_model: R::CreateModel = body.entity;

    let create_model_clone = create_model.clone();

    // Directly create an "ActiveModel" from the "CreateModel", ready to be persisted.
    // By not going through the Model -> ActiveModel conversion, we allow the user to exactly specify the data that should be Set/Unset.
    // It is expected that the conversion does not `Set` attributes on the "ActiveModel" that are disallowed in order to run validations.
    // For example: On entities with a standard `id` field, add `#[ck_create_model(exclude)]`, so that the id is not set but always generated by the db.
    let mut active_model: R::ActiveModel = create_model.into_active_model().await;

    let hook_data = R::HookData::default();

    let hook_data = R::Lifetime::before_create(
        &create_model_clone,
        &mut active_model,
        &context.res_context,
        request.clone(),
        hook_data,
    )
    .await
    .map_err(CrudError::from)?;

    // Run validations before inserting the entity. If critical violations are present, prevent the creation!
    // NOTE: All violations created here can not have an ID, as the entity was not yet saved!
    let trigger = ValidationTrigger::CrudAction(ValidationContext {
        action: CrudAction::Create,
        when: When::Before,
    });
    let partial_validation_results =
        run_entity_validation::<R>(&context.validators, &active_model, trigger);
    if partial_validation_results.has_critical_violations() {
        // Critical validation errors are returned synchronously in the HTTP response.
        // No websocket broadcast needed - the requesting user gets the error directly.
        return Err(CrudError::CriticalValidationErrors {
            violations: partial_validation_results.into(),
        });
    }

    // The entity to insert has no critical violations. The entity can be inserted!
    let inserted_entity: R::Model =
        context
            .repository
            .insert(active_model)
            .await
            .map_err(|err| CrudError::Repository {
                reason: Arc::new(err),
            })?;

    let _hook_data = R::Lifetime::after_create(
        &create_model_clone,
        &inserted_entity,
        &context.res_context,
        request,
        hook_data,
    )
    .await
    .map_err(CrudError::from)?;

    let entity_id = inserted_entity.get_id();
    let serializable_id = entity_id.to_serializable_id();

    // TODO: Performing another conversion into the ActiveModel seems unnecessary. Can we avoid this?
    let active_inserted_entity: R::ActiveModel = inserted_entity.clone().into();

    // Reevaluate the entity for violations and broadcast all of them if some exist.
    let trigger = ValidationTrigger::CrudAction(ValidationContext {
        action: CrudAction::Create,
        when: When::After,
    });

    // TODO: Validate using the model, not the active model? active_inserted_entity would then be obsolete!
    let partial_validation_results =
        run_entity_validation::<R>(&context.validators, &active_inserted_entity, trigger);
    let violations: crudkit_validation::SerializableAggregateViolations =
        partial_validation_results.clone().into();
    let with_validation_errors = partial_validation_results.has_violations();
    if with_validation_errors {
        // Broadcast the PARTIAL validation result to all registered WebSocket connections.
        let mut partial_serializable_validations: PartialSerializableValidations =
            HashMap::from([(String::from(R::TYPE.into()), violations.clone())]);

        // We successfully created the entry at this point. To delete any leftover "create" violations in the frontend, set create to Some empty vector!
        partial_serializable_validations
            .entry(R::TYPE.into().to_owned())
            .and_modify(|s| {
                s.create = Some(Vec::new());
            });

        // Broadcast non-critical validation warnings to all users.
        validation::broadcast_partial_validation_result(&context, partial_serializable_validations)
            .await;

        // Persist the validation results for later access/use.
        let persistable = into_persistable(partial_validation_results);
        context
            .validation_result_repository
            .save_all(persistable)
            .await
            .map_err(|err| CrudError::SaveValidations {
                reason: Arc::new(err),
            })?;
    }

    // Inform all users that the entity was created.
    broadcast_creation_event(&context, serializable_id, with_validation_errors).await;

    // Trigger global validation to check system-wide consistency.
    // Results are broadcast via WebSocket to all connected users.
    run_global_validation::<R>(&context).await;

    Ok(Saved {
        entity: inserted_entity,
        violations,
    })
}

async fn broadcast_creation_event<R: CrudResource>(
    context: &CrudContext<R>,
    serializable_id: SerializableId,
    with_validation_errors: bool,
) {
    if let Err(err) = context
        .collab_service
        .broadcast_json(CollabMessage::EntityCreated(EntityCreated {
            aggregate_name: R::TYPE.into().to_owned(),
            entity_id: serializable_id,
            with_validation_errors,
        }))
        .await
    {
        tracing::warn!("Failed to broadcast entity created: {err:?}");
    }
}
