//! Storage-agnostic data traits for CRUD operations.
//!
//! These traits define the core abstractions for models and fields without
//! coupling to any specific storage backend (like SeaORM).

use crudkit_condition::ConditionClauseValue;
use crudkit_core::Value;
use crudkit_id::Id;
use serde::{de::DeserializeOwned, Serialize};
use std::fmt::Debug;
use std::hash::Hash;

/// Trait for models with typed field access.
///
/// This is the backend equivalent of `CrudModel` from crudkit-web.
/// Each model type (ReadModel, CreateModel, UpdateModel) implements this
/// trait with its own Field enum for typed field access.
pub trait CrudModel: Clone + Debug + Send + Sync + 'static {
    /// The field enum for this model, providing typed access to field values.
    type Field: FieldTrait;
}

/// Trait for field enums that provide typed access to model fields.
///
/// Field enums are generated by derive macros and provide:
/// - Field name access for serialization/querying
/// - Type-safe field value extraction and mutation
pub trait FieldTrait: Clone + Eq + Hash + Debug + Send + Sync + 'static {
    /// Returns the field name as a static string.
    fn name(&self) -> &'static str;
}

/// Trait for looking up fields by name.
///
/// Used for dynamic field access, such as when parsing filter conditions
/// from JSON where field names are provided as strings.
pub trait FieldLookup: Sized {
    /// Attempt to find a field by its string name.
    /// Returns `None` if no field with that name exists.
    fn from_name(name: &str) -> Option<Self>;
}

/// Trait for converting condition values to typed values.
///
/// Used when building queries from parsed filter conditions.
/// Each field knows how to convert a `ConditionClauseValue` to its expected type.
pub trait ConditionValueConverter {
    /// Convert a condition clause value to a typed Value for this field.
    fn convert_condition_value(&self, value: ConditionClauseValue) -> Result<Value, String>;
}

/// Trait for models that have an identifier.
///
/// Not all models have an ID - CreateModel typically doesn't since the ID
/// is generated during insertion. ReadModel and UpdateModel should implement this.
pub trait CrudIdTrait {
    /// The ID type for this model.
    type Id: Id + Clone + Send + Sync + 'static;

    /// Extract the ID from this model instance.
    fn id(&self) -> Self::Id;
}

/// Marker trait for the model type used to create a new entity.
///
/// They typically lack fields which get auto-generated upon first storage by the storage backend.
///
/// No general transformation into any other model type is defined by crudkit. The transformation
/// happens inside the `Repository`.
///
/// Storage integrations, like `crudkit-sea-orm`, however, will provide means to convert a
/// `CreateModel` into the main (persisted) `Model`.
pub trait CreateModelTrait:
    CrudModel + DeserializeOwned + Debug + Clone + Send + Sync + 'static
{
}

/// Marker trait for update models.
///
/// Update models are DTOs used to update existing entities. They may
/// contain the entity's ID for identification.
pub trait UpdateModelTrait:
    CrudModel + DeserializeOwned + Debug + Clone + Send + Sync + 'static
{
}

/// Marker trait for read models.
///
/// Read models represent entities as returned from queries. They always
/// have an ID and are serializable for API responses.
pub trait ReadModelTrait:
    CrudModel + CrudIdTrait + Serialize + Clone + Send + Sync + 'static
{
}

// Blanket implementations for convenience.
impl<T> UpdateModelTrait for T where
    T: CrudModel + DeserializeOwned + Debug + Clone + Send + Sync + 'static
{
}
impl<T> ReadModelTrait for T where
    T: CrudModel + CrudIdTrait + Serialize + Clone + Send + Sync + 'static
{
}
