pub mod migrations;
pub mod newtypes;
pub mod query;
pub mod repo;
pub mod traits;
pub mod validation;

pub use crudkit_sea_orm_macros::*;

// Re-export SeaORM-specific derive macros.
// CkCreateModel and CkUpdateModel are aliased from the SeaORM-specific versions
// for backward compatibility - users continue using the same import paths.
pub use crudkit_sea_orm_macros::{CkSeaOrmCreateModel as CkCreateModel, CkSeaOrmUpdateModel as CkUpdateModel};
pub use derive_crud_columns::CkColumns;
pub use derive_crudkit_id::CkId;
pub use derive_validation_model::CkValidationModel;

// Re-export dependencies used in generated code.
pub use crudkit_condition;
pub use crudkit_core;
pub use crudkit_id;

// Re-export key traits for convenience.
pub use traits::{
    // Adapter traits.
    ApplyToActiveModel, IntoActiveModelForUpdate, IntoSeaOrmActiveModel, SeaOrmResource,
    // Traits generated by derive macros.
    CreateModelTrait, CrudColumns, IdColumns, NewActiveValidationModel, PersistableViolation,
    UpdateActiveModelTrait, UpdateModelTrait, ValidationColumns, ValidatorModel,
};
