pub mod migrations;
pub mod newtypes;
pub mod query;
pub mod repo;
pub mod traits;
pub mod validation;

pub use crudkit_sea_orm_macros::*;

// Re-export derive macros.
pub use crudkit_rs_macros::CkField;
pub use crudkit_sea_orm_macros::CkValidationModel;
pub use crudkit_sea_orm_macros::{CkSeaOrmCreateModel, CkSeaOrmUpdateModel};
pub use crudkit_core_macros::CkId;

// Re-export dependencies used in generated code.
pub use crudkit_core;
pub use crudkit_core::condition as crudkit_condition;
pub use crudkit_core::id as crudkit_id;

// Re-export key traits for convenience.
pub use traits::{
    // Adapter traits.
    ApplyToActiveModel, IntoActiveModelForUpdate, IntoSeaOrmActiveModel, SeaOrmResource,
    // Traits generated by derive macros.
    CrudColumns, IdColumns, NewActiveValidationModel, PersistableViolation, SeaOrmCreateModel,
    SeaOrmUpdateModel, ValidationColumns, ValidatorModel,
};
