//! Wire spelling of field enums generated by the frontend `CkField` derive.

use assertr::prelude::*;
use crudkit_core::Named;
use crudkit_core::Order;
use crudkit_core::request::ReadMany;
use crudkit_core_macros::CkId;
use crudkit_web::model::DynReadField;
use crudkit_web_macros::CkField;
use crudkit_wire_format::v1::ReadManyV1;
use indexmap::IndexMap;
use serde::{Deserialize, Serialize};

#[derive(Clone, PartialEq, Eq, Debug, CkId, CkField, Serialize, Deserialize)]
#[ck_field(model = Read)]
pub struct ReadPerson {
    pub id: i64,
    pub first_name: String,
}

#[test]
fn field_enums_serialize_as_their_field_names() {
    let json = serde_json::to_value(ReadPersonField::FirstName).expect("field should serialize");

    assert_that!(json.clone()).is_equal_to(serde_json::json!("first_name"));
    assert_that!(json).is_equal_to(serde_json::json!(ReadPersonField::FirstName.name()));
    let restored: ReadPersonField =
        serde_json::from_str("\"first_name\"").expect("field name should deserialize");
    assert_that!(restored).is_equal_to(ReadPersonField::FirstName);
}

#[test]
fn erased_ordering_keys_use_the_field_name() {
    let request = ReadMany {
        limit: None,
        skip: None,
        order_by: Some(IndexMap::from([(
            DynReadField::from(ReadPersonField::FirstName),
            Order::Asc,
        )])),
        condition: None,
    };

    let json = serde_json::to_value(ReadManyV1::from(request)).expect("request should serialize");
    assert_that!(json["order_by"].clone()).is_equal_to(serde_json::json!({ "first_name": "asc" }));
}
