[package]
name = "crudkit-yew"
version = "0.1.0"
edition = "2021"

[dependencies]
crudkit-condition = { path = "../../../crudkit-condition" }
crudkit-id = { path = "../../../crudkit-id/crates/crudkit-id" }
crudkit-shared = { path = "../../../crudkit-shared" }
crudkit-validation = { path = "../../../crudkit-validation" }
crudkit-web = { path = "../../../crudkit-web/crates/crudkit-web" }
crudkit-websocket = { path = "../../../crudkit-websocket" }
derive-crud-action-payload = { path = "../../../crudkit-web/crates/derive-crud-action-payload" }
derive-crud-resource = { path = "../../../crudkit-web/crates/derive-crud-resource" }
derive-crud-selectable = { path = "../../../crudkit-web/crates/derive-crud-selectable" }
derive-crudkit-id = { path = "../../../crudkit-id/crates/derive-crudkit-id" }
derive-field = { path = "../../../crudkit-web/crates/derive-field" }
derive-field-value = { path = "../../../crudkit-web/crates/derive-field-value" }

async-trait = "0.1.71"
derive_more = "0.99.17"
dyn-clone = "1.0.12"
gloo = "0.10.0"
indexmap = { version = "2.0.0", features = ["serde"] }
js-sys = "0.3.64"
once_cell = "1.18.0"
parking_lot = "0.12.1"
reqwest = { version = "0.11.18", default-features = false, features = [
    "json",
    "multipart",
] }
serde = { version = "1.0.171", features = ["derive"] }
serde-wasm-bindgen = "0.5.0"
serde_json = { version = "1.0.103", features = ["raw_value"] }
thiserror = "1.0.43"
time = { version = "0.3.23", features = [
    "macros",
    "local-offset",
    "wasm-bindgen",
] }
tracing = "0.1.37"
urlencoding = "2.1.2"
uuid = { version = "1.4.0", features = ["js", "v4", "v7", "serde"] }
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = [
    "Document",
    "Element",
    "HtmlElement",
    "HtmlInputElement",
    "DomTokenList",
    "Event",
    "EventTarget",
    "DomRect",
] }
yew = "0.20.0"
yew-bootstrap-icons = { git = "https://github.com/lpotthast/yew-bootstrap-icons" }
yew-tiptap = { git = "https://github.com/lpotthast/yew-tiptap" }
yewdux = "0.9.3"
